/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package picselectertester;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;

/**
 *
 * @author Nils-Inge
 */
public class pictureForm extends javax.swing.JFrame {

    /**
     * Creates new form pictureForm
     */
    public pictureForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dpPicture = new javax.swing.JDesktopPane();
        lblPictureStorage = new javax.swing.JLabel();
        btnVisaBild = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblPictureStorage.setText("jLabel1");

        javax.swing.GroupLayout dpPictureLayout = new javax.swing.GroupLayout(dpPicture);
        dpPicture.setLayout(dpPictureLayout);
        dpPictureLayout.setHorizontalGroup(
            dpPictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpPictureLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPictureStorage, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        dpPictureLayout.setVerticalGroup(
            dpPictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpPictureLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPictureStorage, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        dpPicture.setLayer(lblPictureStorage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnVisaBild.setText("Visa bild");
        btnVisaBild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisaBildActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(btnVisaBild))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(dpPicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(dpPicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVisaBild)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Image ScaledImage (Image img , int bredd, int höjd){
        BufferedImage resizedImage = new BufferedImage (bredd, höjd, BufferedImage.TYPE_INT_RGB);   // innehåller den anpassade bilden
        
        Graphics2D g = resizedImage.createGraphics ();
        g.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g.drawImage(img, 0, 0, bredd, höjd, null);
        g.dispose();
        
        return resizedImage;
    }
    
    
    private void btnVisaBildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaBildActionPerformed
        try {
            
            Connection connection = DriverManager.getConnection("jdbc:mysql://resadb.cnjxqasdqhys.us-west-2.rds.amazonaws.com:3306/resaDB", "resaDB", "resaDB1234");

            Statement myStmt = connection.createStatement();
            
            String sql = "select bild from BildTest where BildID = 5";
           
            ResultSet myRes = myStmt.executeQuery(sql);

            if (myRes.next()) {                                 // Fyller byte array med bytes från DB
                byte[] dataImage = myRes.getBytes("bild");      // Kolumnnamnet för bilden anges här
                imc = new ImageIcon (dataImage);                // Skapar ett nytt ikonobjekt som består utav bytearrayen 
                
                //Scaling: anpassar storleken på bilden
                Image imgStore = imc.getImage();                                          // Skapar ett nytt bildobjekt som hämtar bildikonen 
                imgStore = imgStore.getScaledInstance(200, 200, Image.SCALE_SMOOTH);      // Justerar storleken på det nya bildobjektet efter width och height
                imc = new ImageIcon(imgStore);                                            // stoppar in den justerade bilden i det gamla ImageIcon-objektet som nu har anpassats   
                
                // Den anpassade bilden stoppas in i en jLabel
                lblPictureStorage.setIcon(imc); // bilden lagras i labeln lblPictureStorage
                
                
            }
        } catch (Exception e) {
            e.printStackTrace();
            
        }
    }//GEN-LAST:event_btnVisaBildActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pictureForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pictureForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pictureForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pictureForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pictureForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVisaBild;
    private javax.swing.JDesktopPane dpPicture;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPictureStorage;
    // End of variables declaration//GEN-END:variables


private ImageIcon imc = null;

}

